language: python
sudo: false

python:
 - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"

cache: pip

install:
   - pip install -r requirements.txt
   - sudo apt update
#     - sudo apt upgrade
   - sudo apt install -y python-pip
   - sudo apt install build-essential libssl-dev libffi-dev python-dev
   - pip install pytest
#     - pip install -r requirements.txt
script:
   - python ex1.py
#   - sleep 3
#   - python ex12.py
#   - sleep 3
#   - python ex13.py
#   - sleep 3
#   - python ex14.py
#   - sleep 3
#   - python ex15.py
#   - sleep 3
#   - python ex16.py
#   - sleep 3
#   - python ex17.py
#     - python ex1.py
  
